server:
  port: 8086

spring:
  main:
    allow-circular-references: true
  application:
    name: knight-practice-demo

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html # the path of swagger-ui
    tags-sorter: alpha # sort tags
    operations-sorter: alpha # sort operations
  api-docs:
    path: /v3/api-docs # the path of api-docs
  group-configs:
    - group: 'default' # default group
      paths-to-match: '/**' # the path to match
      packages-to-scan: io.github.charlie.controller # the package to scan
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true